model = "gpt-5.5"
model_reasoning_effort = "medium"
personality = "pragmatic"

[windows]
sandbox = "elevated"

[features]
multi_agent = true

[projects.'C:\Users\gladwell']
trust_level = "trusted"

[projects.'C:\code\rc']
trust_level = "trusted"

[projects.'C:\code\codex1']
trust_level = "trusted"

[projects.'C:\']
trust_level = "trusted"

[projects.'C:\code\ds']
trust_level = "trusted"

[projects.'C:\code\dc']
trust_level = "trusted"

[projects.'\\?\UNC\wsl.localhost\Ubuntu\home\gladwell\discourse']
trust_level = "trusted"

[projects.'C:\code\sr\cx']
trust_level = "trusted"

[projects.'C:\code\sr\ym']
trust_level = "trusted"

[projects.'c:\code\mc']
trust_level = "trusted"

[projects.'c:\code\codex']
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
